### ISSUE TITLE
is glsl.heroku.com's server down?

### ISSUE THREAD

**Issue by erichlof** [mrdoob/glsl-sandbox#38]
Hi @mrdoob ,
I have a couple of older shaders from glsl.heroku.com bookmarked for reference.  Recently when trying to visit these pages, it reads "Application Error".
Is the server for glsl.heroku.com down, and more importantly - where did all those older fragment shaders go?  Can they be retrieved somehow?

**Comment by dorald** [comment]
the old glsl.heroku.com is down..!
you can use http://glslsandbox.com/

**Comment by emackey** [comment]
Correct, edit the bookmarks and replace just the hostname `glsl.heroku.com` with the new hostname `glslsandbox.com`.  The shader numbers are the same, so the rest of the link will still work.

**Comment by erichlof** [comment]
Ok thanks for the info @dorald and the tip, @emackey !  :)

**Comment by gre** [comment]
can you update the link on this repo please?

**Comment by mrdoob** [comment]
> can you update the link on this repo please?

Ops! Fixed 😇
