### ISSUE TITLE
uniform sampler2D backbuffer

### ISSUE THREAD

**Issue by wangjiangchuan** [mrdoob/glsl-sandbox#48]
what is the sampler2D? is it a black picture? I don't know it at all. If it is a picture, can I find it in the github code?

**Comment by emackey** [comment]
It's a texturemap of the previous animation frame.  It can be used to have effects propagate from one frame to the next.

For example, it can be used to implement Conway's Game of Life:

http://glslsandbox.com/e#207.3

**Comment by wangjiangchuan** [comment]
Thank you a lot. I understand it. It just like when you move you mouse, backbuffer is the last pisition of your mouse.

**Comment by emackey** [comment]
Can you close this issue?  Thanks!
