### ISSUE TITLE
Sample library it's full of nazi symbol......

### ISSUE THREAD

**Issue by giorgionetg** [mrdoob/glsl-sandbox#55]
Thanks for cleaning this awkward stuff... 👍 

it's just an example. And it's just full of these!

http://glslsandbox.com/e#51458.0

**Comment by DagAgren** [comment]
The issue for doing any kind of moderation was closed: 
https://github.com/mrdoob/glsl-sandbox/issues/36

**Comment by mrdoob** [comment]
Duplicate of #36 indeed.
