### ISSUE TITLE
The server doesn't respond.

### ISSUE THREAD

**Issue by Mehran7kl** [mrdoob/glsl-sandbox#81]
Recently glslsandbox , shadertoy and some other servers don't respond me(but with using VPN it's working). I guess "U.S sanctions against Iran" caused this( because they now are being returned again) do you follow U.S sanctions  or proxies block my request? which country your hosts located in?

**Comment by jfontan** [comment]
We don't have filters for any country. The server is running in a VM in Amsterdam. Maybe is the company or some ISP in between that is blocking the traffic.
