### ISSUE TITLE
API Access

### ISSUE THREAD

**Issue by magistermaks** [mrdoob/glsl-sandbox#86]
I was creating a web app that allows a user to import a shader from an external source by pasting in a link
i first implemented it for shadertoy links, no problems there. But the request to GLSL Sandbox is blocked and failes:

![Screenshot from 2023-08-10 12-15-10](https://github.com/mrdoob/glsl-sandbox/assets/53909807/465e0241-4746-4689-ad10-319991a2b642)

Could this maybe be changed so that external access is allowed?   
Should be as simple as adding the `Access-Control-Allow-Origin: *` header.

**Comment by jfontan** [comment]
I've updated `/item` endpoint to add that header. If you need this configuration in any other endpoint tell me and add it for others.

```
> GET /item/105400.0 HTTP/2
> Host: glslsandbox.com
> User-Agent: curl/8.2.1
> Accept: */*
> Origin: https://example.reqbin.com
>
< HTTP/2 200
< access-control-allow-origin: *
< content-type: application/json
< vary: Origin
< date: Fri, 18 Aug 2023 20:02:10 GMT
```

**Comment by magistermaks** [comment]
The `/item` one should suffice, thanks!
